---
 - hosts: all
   user: dwarika

   vars_files:
   - secret

   tasks:
   - name: apt remove packagename
     apt:
      name: '{{ package }}'
      update_cache: true
      state: absent
     become: yes

