---
 - hosts: all
   user: dwarika

   vars_files:
   - secret

   tasks:
   - name:  apt update
     apt:
      update_cache: yes
      cache_valid_time: 3600
      install_recommends: yes
      upgrade: true
     become: true
